Save & Load player journal settings
CholiCub/A-Journey-For-Love pull request #1
Opened 2022-11-16 04:56 UTC by CholiCub

2022-11-16 05:24 UTC, Rosuavio commented
@CholiCub, I will try to take a look soon

2022-11-17 06:11 UTC, Rosuavio requested changes
There are a few things that can be improved and will help keep the code maintainable and clear. The most important thing is that you should know what everything is doing and what is is meant for, or at least be able to figure it out. And once you can do that remove anything that is not needed and simplify things as much as possible.

2022-11-17 06:11 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
A few things, if this is a member function then is has access to its object `this` so why would you need to take a `Player` as a parameter. 
Does this function serialize the current object's data?
```cpp
foo.ToJson(j, p, f);
/\
```
or the does it serialize the parameter's data?
```cpp
foo.ToJson(j, p, f);
             /\
```

2022-11-17 06:11 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
This function takes a few parameters that can be used as a "where to put the data" this makes the function not clear on how it behaves or how it is meant to be used. Does it put data into `j` or does it write the data to the file at `dfile`?

2022-11-17 06:11 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
If you fallow https://github.com/nlohmann/json#basic-usage some this all becomes more clear. 
1) `to_json` and `from_json` are not member function so they don't access to `this` and calls to them looks like `to_json(jsonObjecToPutDataInfo, personObjectToSerilizeDataFrom)` and `from_json(jsonObjectToGetDataFrom, personObjectToDerserilizeTo)` those functions are clear in what the parameters are for.

2023-03-17 01:58 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
> +const string defaultPlayerJournalSettingsFile = "PlayerJournalSettings.json";
Fixed in [7731a62](https://github.com/CholiCub/A-Journey-For-Love/pull/1/commits/7731a6235b7134a9b8f4e7087862319ea2d71940)

2023-03-17 02:45 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
> +bool ReturningPlayer(Player p) {
Fixed 7e78e8458ef234354e9f5c8c481ed3853c3f9390

2023-03-17 02:53 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
> +json j;
Fixed dc99b8e6a58f010973445e6f611905a517ff6f09

2023-03-17 02:53 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
> +bool ReturningPlayer(Player p) {
I see in that commit you did more than just what is in the message or you comment. 

Being more descriptive in your comments not just your commits helps because they are connected to the conversation, you could have wrote "Changed the function to use its parameter instead of he global" https://github.com/CholiCub/A-Journey-For-Love/commit/7e78e8458ef234354e9f5c8c481ed3853c3f9390 instead of just "Fixed", "Fixed" is fine when its simple.

2023-03-17 03:02 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
>  		PartnerPreferenceToString(PartnerPreference(partnerPreferenceNum)));
Will fix formatting later in another pr

2023-03-17 03:05 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
> +template <class myType> void PrintQuestionOptions(const int numOfOptions, string(*s)(myType)) {
Next time will keep it separate and clean

2023-03-17 03:28 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
Fixed formatting d78617b9d30e5835556b7def3bf95c59a0df73a2

2023-03-17 03:29 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
Looks great! :smiley:

2023-06-11 03:48 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
Updated Player class after changing how json serialization read and saves were made. No longer have unnecessary default constructor.
Please see 6b6e004a124b22c881c928b97030df70b9591110

2023-06-11 03:55 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
I now have JsonPersistance class handling all json reading and writing to file. I am also having my parameterized player constructor take in deserialized player data. 
Please see e65f64ed0c8ed2e97169f65a29ae70592894268f

2023-06-11 03:58 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
Love the changes! Its much better now!

2023-06-11 03:59 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
Update player class (it no longer handles json/file reading and writing) and added a jsonpersistance class.
Please see e65f64ed0c8ed2e97169f65a29ae70592894268f

2023-06-11 03:59 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
Ooo, very nice!

2023-06-11 04:02 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/Player.cpp
> +}
I see the function parameters are cleaned up in the new persistence class (what I asked for here). Love it!

2023-06-11 04:03 UTC, Rosuavio commented
Really good fixes @CholiCub! I do see somethings that could use some work still so I will try to have another review ready shortly.

2023-06-11 05:08 UTC, Rosuavio requested changes
Looking at lot better, but I think a few things can improve the code a whole lot! Getting there though!

2023-06-11 05:08 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/BodyType.cpp
> +}
This function seems to be written exactly the same in all the classes that inherit from `Properties`. I wounder if you can avoid having to write the same code in all these places by having one definition in `Properties`?

2023-06-11 05:08 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +	ofs.close();
Instead of opening the file, prepping the json and then writing the json to the file. I wonder if you can prep the json first, open the file, write the json and then close the file to keep the file open for less time. Not a big deal, but I know file handles are an OS resource and might as well hold on to a file for as short of time as you can.

2023-06-11 05:08 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +	ifs.close();
I don't know if it would work, but could you also minimize the time you have the file open here too? Maybe if you close the file right after you parse it into `data`? Not entirely sure that will work tbh, but its worth trying.

2023-06-11 05:08 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +}
Nice, but what if the file does not exist?

2023-06-11 05:13 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.h
> +};
I see what you mean. Would PlayerPersistence be better?

2023-06-11 05:15 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.h
> +};
Yeah I think so!

2023-06-11 05:16 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
> +	if (IsReturningPlayer()) {
I didn't realize that the function was reduced to the one line. Thanks, will make the change.

2023-06-11 05:17 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
> +}
Good point, will look into making that change.

2023-06-11 05:18 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/BodyType.cpp
> +}
Another amazing point. Will make the change. Thanks!

2023-06-11 05:20 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +	ofs.close();
Hmm... okay will look into this. Thanks for pointing this flaw out.

2023-06-11 05:21 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +}
I will make the necessary correction.

2023-06-11 05:22 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +	ifs.close();
Will try to.

2023-06-11 06:11 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +}
Fixed 0724de4601b2cc481e6cf540d51bf6425135834e

2023-06-11 06:12 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
> +	if (IsReturningPlayer()) {
Fixed 42603db44ce128a8b9e892b0cab2d22e05cf6a21

2023-06-11 06:26 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.h
> +};
Fixed b38eac283f34af0bace94831d2020f0971c2f024

2023-06-11 22:28 UTC, Rosuavio reviewed
A few more things that that might be worth looking into.

2023-06-11 22:28 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +bool PlayerPersistence::IsFileEmpty() {
Is this name still appropriate? Now its doing two things, maybe a more abstract name would be more appropriate?

2023-06-11 22:28 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +	if (!ifs.fail()) {
Does that set empty to false by default? If the condition in the next if statement is false then this function will return whatever empty is initialized with and its not clear what value that is.

2023-06-11 22:29 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +}
Good, but I had some comments on the new changes. Might not be a big deal, but worth looking into https://github.com/CholiCub/A-Journey-For-Love/pull/1#pullrequestreview-1473845383

2023-06-14 21:55 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
> +}
Updated a1c19b211949ec075ad32bf0f6d1f0fe25683086

2023-06-17 22:06 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/PersonPersistence.h
> +
Removed PersonPersistence cf1f031724b7a6f223bde5d2ef23ade38e7c5f53

2023-06-17 23:33 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/BodyType.cpp
> +}
Moved IsValidIntInEnum() into the Properties base class ed72711341ad2a3e4cdadfd8fda42b766fdc7d9b

2023-06-17 23:40 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +	ofs.close();
Moved some lines over bcbeba9eea18286c13a060e9ce75da16d441397b

2023-06-17 23:53 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/PersonPersistence.h
> +
Nice :+1:

2023-06-17 23:55 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +	ifs.close();
4d3b1371bf32c67a757c407e8c7117e7bf376249

2023-06-17 23:57 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/BodyType.cpp
> +}
Awesome :+1:
Any change that removes that safely removes that many lines, and is easy to understand, is a great change!

2023-06-17 23:57 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +	ofs.close();
Nice!

2023-06-18 00:04 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +}
Made naming change 6a0dc72fbccc13edf876a5471536c96637ef9d56

2023-06-18 00:04 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +bool PlayerPersistence::IsFileEmpty() {
6a0dc72fbccc13edf876a5471536c96637ef9d56

2023-06-18 00:09 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +}
Here this too f3b43732e77d968148342b280fc11e981974ad9b

2023-06-18 00:09 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +}
I forgot lol

2023-06-18 00:10 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +bool PlayerPersistence::IsFileEmpty() {
Nice.

2023-06-18 00:18 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +	if (!ifs.fail()) {
779ea83628f481e275b6d57bdcd984507fe052c3

2023-06-18 00:21 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/JsonPersistence.cpp
> +	ifs.close();
My lack of knowledge of cpp makes me feel unsure if closing `ifs` while we are still using `data` is safe. We want to keep the change in 4d3b1371bf32c67a757c407e8c7117e7bf376249, but can you test that it works locally.

2023-06-18 00:38 UTC, Rosuavio reviewed
Some things standout about `PlayerPersistence::IsEmpty()`. Also it might be worth manually testing a few cases with it. What happens when there is a save present, what about when there is no save present?

2023-06-18 00:38 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +		ifs.open(DEFAULT_PLAYER_JOURNAL_SETTINGS_FILE);
Does `DEFAULT_PLAYER_JOURNAL_SETTINGS_FILE` need to be passed to the constructor of `ifstream` and `ifs.open`?

2023-06-18 00:38 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +	return empty;
I am not sure under what conditions `ifs.fail()` will return `true` or `false`, but it seems like if it returns `true`, then the code in the `if` will not be run and we will return `false`. So if `ifs.fail()` returns true if the file does not exist then `IsEmpty` will return false. So if it fails to open the file, it is not empty?

2023-06-18 00:38 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +		ifs.open(DEFAULT_PLAYER_JOURNAL_SETTINGS_FILE);
The docs seem to suggest that when you pass a file name to the constructor or `ifstream`, it will call open automatically. https://en.cppreference.com/w/cpp/io/basic_ifstream/basic_ifstream

2023-06-18 00:46 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/Main.cpp
>  	}
If `pp.IsEmpty()` we `pp.read()` in a player, and if `pp.IsEmpty()` if not true (there is a saved player) we create one?

2023-06-18 00:51 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.h
> +	virtual Player read();
There is no class that derives from `PlayerPresistence`, does `read()` need to be marked as `virtual`?

2023-06-18 00:52 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +		ifs.open(DEFAULT_PLAYER_JOURNAL_SETTINGS_FILE);
1a3abd3c40b306e5c4b2ee49ccbc8e8b9bc624ae

2023-06-18 00:54 UTC, Rosuavio commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +}
Because you return before `ifs.close()`, you never close the file. This could leave it locked by the OS so nothing can use it, and maybe even this program can't open it again later.

2023-06-18 09:29 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.h
> +	virtual Player read();
8f98e3a8c2233041fb01944e8c1837eba4774fd5

2023-06-18 09:29 UTC, CholiCub commented on AJourenyForLove-Text-BasedAdventureGame/PlayerPersistence.cpp
> +}
ee0c178c43037514e5d1080b03c138f85a07bb48

2023-06-18 09:31 UTC, merged